export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  allergens?: string[];
  notes?: string;
}

export const menuCategories = [
  'Vorspeisen Kalt',
  'Vorspeisen Warm',
  'Suppen',
  'Nudel Gerichte',
  'Kleine Köstlichkeiten',
  'Spezialitäten vom Grill',
  'Schnitzel',
  'Putensteak Spezialitäten',
  'Pfannengerichte',
  'Internationale Spezialitäten',
  'Steaks',
  'Fisch',
  'Vegetarisch',
  'Salatplatten',
  'Für Kinder',
];

export const menuItems: MenuItem[] = [
  {
    id: '01',
    name: 'Dalmatinische kalte Platte',
    description: 'luftgetrockneter Dalmatinischer Schinken, Manchego-Käse, Oliven und Brot',
    price: 11.90,
    category: 'Vorspeisen Kalt',
    allergens: ['Gluten'],
  },
  {
    id: '03',
    name: 'Krabben-Cocktail',
    description: 'mit Butter und Toast',
    price: 11.90,
    category: 'Vorspeisen Kalt',
    allergens: ['Gluten', 'Milch'],
  },
  {
    id: '05',
    name: 'Geräucherter Lachs',
    description: 'mit Sahnemeerrettich, Butter und Toast',
    price: 11.90,
    category: 'Vorspeisen Kalt',
    allergens: ['Fisch', 'Milch', 'Gluten'],
  },
  {
    id: '06',
    name: 'Handkäse mit Musik',
    description: 'dazu Butter und Brot',
    price: 8.00,
    category: 'Vorspeisen Kalt',
    allergens: ['Milch', 'Gluten'],
  },
  {
    id: '07',
    name: '1/2 Dtzd. Weinbergschnecken',
    description: 'mit Toast',
    price: 9.90,
    category: 'Vorspeisen Warm',
    allergens: ['Gluten'],
  },
  {
    id: '08',
    name: 'Champignons, gebraten',
    description: 'mit Butter, Knoblauch und Toast',
    price: 8.70,
    category: 'Vorspeisen Warm',
    allergens: ['Milch', 'Gluten'],
  },
  {
    id: '09',
    name: 'Panierte Champignonköpfe',
    description: 'mit Remouladensauce und Toast',
    price: 9.90,
    category: 'Vorspeisen Warm',
    allergens: ['Gluten', 'Ei'],
  },
  {
    id: '11',
    name: 'Schafskäse paniert',
    description: 'mit Remouladensauce und Toast oder unpaniert mit Ajvar und Zwiebeln',
    price: 9.90,
    category: 'Vorspeisen Warm',
    allergens: ['Milch', 'Gluten', 'Ei'],
  },
  {
    id: '12',
    name: 'Camembert gebacken',
    description: 'mit Preiselbeeren und Toast',
    price: 9.90,
    category: 'Vorspeisen Warm',
    allergens: ['Milch', 'Gluten', 'Ei'],
  },
  {
    id: '13',
    name: 'Rinderkraftbrühe',
    description: 'mit Einlage oder Ei oder Markklößchen',
    price: 6.50,
    category: 'Suppen',
    allergens: ['Gluten', 'Ei'],
  },
  {
    id: '16',
    name: 'Hausgemachte Gulaschsuppe',
    description: 'Traditionelle kroatische Küche',
    price: 5.80,
    category: 'Suppen',
    allergens: ['Gluten'],
  },
  {
    id: '17',
    name: 'Broccoli-Cremesuppe',
    description: 'mit Mandelspitzen',
    price: 6.40,
    category: 'Suppen',
    allergens: ['Milch', 'Nüsse'],
  },
  {
    id: '14',
    name: 'Tomatencremesuppe',
    description: 'mit Sahnehäubchen',
    price: 5.80,
    category: 'Suppen',
    allergens: ['Milch'],
  },
  {
    id: '18',
    name: 'Spaghetti mit Tomatensoße',
    description: 'klassisch italienisch',
    price: 10.80,
    category: 'Nudel Gerichte',
    allergens: ['Gluten'],
  },
  {
    id: '19',
    name: 'Spaghetti mit Soße Bolognese',
    description: 'mit Rinderhackfleisch',
    price: 11.70,
    category: 'Nudel Gerichte',
    allergens: ['Gluten'],
  },
  {
    id: '20',
    name: 'Makkaroni Cardinale',
    description: 'klassisches Nudelgericht',
    price: 11.70,
    category: 'Nudel Gerichte',
    allergens: ['Gluten'],
  },
  {
    id: '21',
    name: 'Bandnudeln mit Lachs in Currysoße',
    description: 'exotisch würzig',
    price: 14.80,
    category: 'Nudel Gerichte',
    allergens: ['Gluten', 'Fisch', 'Milch'],
  },
  {
    id: '22',
    name: 'Bandnudeln a la olio',
    description: 'auf Olivenöl mit frischen Gemüsesorten und Speck',
    price: 14.20,
    category: 'Nudel Gerichte',
    allergens: ['Gluten'],
  },
  {
    id: '23',
    name: 'Pljeskavica',
    description: 'mit Duvecreis und Salat',
    price: 10.40,
    category: 'Kleine Köstlichkeiten',
    allergens: ['Gluten'],
    notes: 'Kroatische Spezialität',
  },
  {
    id: '24',
    name: 'Truthahnsteak',
    description: 'mit Tomatenscheiben und Käse überbacken, dazu Brokkoli und Salat',
    price: 12.90,
    category: 'Kleine Köstlichkeiten',
    allergens: ['Milch'],
  },
  {
    id: '25',
    name: 'Lammrückensteak',
    description: 'mit Duvecreis und Salat',
    price: 14.80,
    category: 'Kleine Köstlichkeiten',
    allergens: ['Gluten'],
  },
  {
    id: '26',
    name: 'Toast Split',
    description: 'kleines Rumpsteak mit Champignons, Speck und gebratenen Zwiebeln auf Toast',
    price: 18.60,
    category: 'Kleine Köstlichkeiten',
    allergens: ['Gluten'],
  },
  {
    id: '27',
    name: 'Hawaii Toast',
    description: 'mit Ananas',
    price: 10.10,
    category: 'Kleine Köstlichkeiten',
    allergens: ['Gluten'],
  },
  {
    id: '28',
    name: 'Venezia Toast',
    description: 'zwei Schweinefilets auf Toast mit Rahmchampignonsoße und Salatgarnitur',
    price: 15.00,
    category: 'Kleine Köstlichkeiten',
    allergens: ['Gluten', 'Milch'],
  },
  {
    id: '29',
    name: 'Cevapcici',
    description: 'mit Pommes frites, Duvecreis und Salat',
    price: 13.70,
    category: 'Spezialitäten vom Grill',
    allergens: ['Gluten'],
    notes: 'Kroatische Grillspezialität',
  },
  {
    id: '30',
    name: 'Raznjici (zwei Spieße vom Schweinekamm)',
    description: 'mit Pommes frites, Duvecreis und Salat',
    price: 14.50,
    category: 'Spezialitäten vom Grill',
    allergens: ['Gluten'],
    notes: 'Kroatische Grillspezialität',
  },
  {
    id: '31',
    name: 'Pola Pola (ein Spieß und 4 Cevapcici)',
    description: 'mit Pommes frites, Duvecreis und Salat',
    price: 14.20,
    category: 'Spezialitäten vom Grill',
    allergens: ['Gluten'],
  },
  {
    id: '32',
    name: 'Pljeskavica (Hacksteak)',
    description: 'mit Pommes frites, Duvecreis und Salat',
    price: 13.00,
    category: 'Spezialitäten vom Grill',
    allergens: ['Gluten'],
  },
  {
    id: '33',
    name: 'Pljeskavica-Spezial',
    description: 'gefüllt mit Käse, dazu Pommes frites, Duvecreis und Salat',
    price: 15.50,
    category: 'Spezialitäten vom Grill',
    allergens: ['Gluten', 'Milch'],
  },
  {
    id: '34',
    name: 'Zagrebteller',
    description: 'Pljeskavica, Schweineschnitzel, Speck, zwei Cevapcici mit Pommes frites, Duvecreis und Salat',
    price: 17.10,
    category: 'Spezialitäten vom Grill',
    allergens: ['Gluten'],
    notes: 'Aus Zagreb inspiriert',
  },
  {
    id: '35',
    name: 'Grillteller',
    description: 'zwei Cevapcici, gefülltes Hacksteak, Schweineschnitzel, Putensteak, Speck mit Pommes frites, Duvecreis und Salat',
    price: 17.80,
    category: 'Spezialitäten vom Grill',
    allergens: ['Gluten'],
  },
  {
    id: '36',
    name: 'Mix-Grill-Spezial',
    description: 'Rinderfilet, Rumpsteak, Schweinelende, Lammkotelett mit Kräuterbutter, Käse, paniert mit Bratkartoffeln und Salat',
    price: 24.70,
    category: 'Spezialitäten vom Grill',
    allergens: ['Gluten', 'Milch'],
  },
  {
    id: '37',
    name: 'Leber vom Grill',
    description: 'mit Röstzwiebeln, Bratkartoffeln und Salat',
    price: 12.50,
    category: 'Spezialitäten vom Grill',
    allergens: [],
  },
  {
    id: '38',
    name: 'Spieß Dalmatinischer Art',
    description: 'drei Sorten Fleisch vom Grill mit Rostzwiebeln, Pommes frites, Duvecreis, Gemüse und Salat',
    price: 17.70,
    category: 'Spezialitäten vom Grill',
    allergens: ['Gluten'],
  },
  {
    id: '39',
    name: 'Bauerspieß',
    description: 'Cevapcici, Speck, gefülltes Hacksteak, Schweineschnitzel mit Pommes frites, Duvecreis und Salat',
    price: 17.20,
    category: 'Spezialitäten vom Grill',
    allergens: ['Gluten'],
  },
  {
    id: '40',
    name: 'Schweinelendenspieß',
    description: 'mit Zwiebeln und Paprika, dazu Duvecreis, Tomatensoße und Salat',
    price: 20.70,
    category: 'Spezialitäten vom Grill',
    allergens: ['Gluten'],
  },
  {
    id: '41',
    name: 'Lamm-Medaillons (Café de Paris)',
    description: 'dazu Schwenkkartoffeln, grüne Bohnen, Kräuterbutter und Salat',
    price: 21.00,
    category: 'Spezialitäten vom Grill',
    allergens: [],
  },
  {
    id: '814',
    name: 'Paniertes Schnitzel nach Wiener Art',
    description: 'Schweinschnitzel mit Pommes frites und Salat vom Buffet',
    price: 11.00,
    category: 'Schnitzel',
    allergens: ['Gluten', 'Ei'],
    notes: 'Donnerstags Schnitzeltag',
  },
  {
    id: '815',
    name: 'Schnitzel Jäger Art',
    description: 'mit delikater Jägersauce, Pommes frites und Salat',
    price: 11.00,
    category: 'Schnitzel',
    allergens: ['Gluten', 'Ei'],
    notes: 'Donnerstags Schnitzeltag',
  },
  {
    id: '816',
    name: 'Paprika Schnitzel',
    description: 'paniert mit würziger Paprika-Sauce, Pommes frites und Salat',
    price: 11.00,
    category: 'Schnitzel',
    allergens: ['Gluten', 'Ei'],
    notes: 'Donnerstags Schnitzeltag',
  },
  {
    id: '817',
    name: 'Schnitzel Mexikanische Art',
    description: 'mit feuriger Sauce, Pommes frites und Salat',
    price: 11.00,
    category: 'Schnitzel',
    allergens: ['Gluten', 'Ei'],
    notes: 'Donnerstags Schnitzeltag',
  },
  {
    id: '818',
    name: 'Schnitzel mit Sauce Bolognese',
    description: 'paniert mit Bolognese, Pommes frites und Salat',
    price: 11.00,
    category: 'Schnitzel',
    allergens: ['Gluten', 'Ei'],
    notes: 'Donnerstags Schnitzeltag',
  },
  {
    id: '831',
    name: 'Zwiebelschnitzel',
    description: 'mit Röstzwiebeln, Pommes frites und Salat',
    price: 11.00,
    category: 'Schnitzel',
    allergens: ['Gluten', 'Ei'],
    notes: 'Donnerstags Schnitzeltag',
  },
  {
    id: '832',
    name: 'Pfefferschnitzel',
    description: 'mit pikanter Pfeffer-Sauce, Pommes frites und Salat',
    price: 11.00,
    category: 'Schnitzel',
    allergens: ['Gluten', 'Ei'],
    notes: 'Donnerstags Schnitzeltag',
  },
  {
    id: '834',
    name: 'Rahmschnitzel',
    description: 'mit feiner Rahmsauce, Pommes frites und Salat',
    price: 11.00,
    category: 'Schnitzel',
    allergens: ['Gluten', 'Ei', 'Milch'],
    notes: 'Donnerstags Schnitzeltag',
  },
  {
    id: '833',
    name: 'Knusperschnitzel',
    description: 'mit Cornflakes, Pommes frites und Salat',
    price: 12.00,
    category: 'Schnitzel',
    allergens: ['Gluten', 'Ei'],
    notes: 'Donnerstags Schnitzeltag',
  },
  {
    id: '42',
    name: 'Putensteak-Toskana',
    description: 'mit Soße Hollandaise, Brokkoli, Petersilienkartoffeln und Salat',
    price: 18.00,
    category: 'Putensteak Spezialitäten',
    allergens: ['Ei', 'Milch'],
  },
  {
    id: '43',
    name: 'Putenbrust Cordon bleu',
    description: 'gefüllt mit Käse, dazu Soße Hollandaise, Pommes frites, Gemüse und Salat',
    price: 19.00,
    category: 'Putensteak Spezialitäten',
    allergens: ['Milch', 'Ei'],
  },
  {
    id: '44',
    name: 'Hawaii Schnitzel',
    description: 'Putenbrust mit Ananas und Käse überbacken, dazu Kroketten und Salat',
    price: 18.40,
    category: 'Putensteak Spezialitäten',
    allergens: ['Milch', 'Ei'],
  },
  {
    id: '45',
    name: 'Putengeschnetzeltes',
    description: 'mit Butterreis, frischen Champignons in Rahmsoße und Salat',
    price: 19.80,
    category: 'Pfannengerichte',
    allergens: ['Milch'],
  },
  {
    id: '46',
    name: 'Saute Stroganoff',
    description: 'geschmortes, geschnetzeltes Rinderfilet mit delikater Soße, Butterreis und Salat',
    price: 24.70,
    category: 'Pfannengerichte',
    allergens: ['Milch'],
  },
  {
    id: '47',
    name: 'Dubrovnik Pfanne',
    description: 'verschiedene Filetwürfel mit Champignons in Sahnesoße, Bratkartoffeln und Salat',
    price: 23.00,
    category: 'Pfannengerichte',
    allergens: ['Milch'],
    notes: 'Aus Dubrovnik inspiriert',
  },
  {
    id: '48',
    name: 'Jäger Pfanne',
    description: 'Schweinelende, Rumpsteak, Putensteak mit Champignonköpfen in Jägersoße, Bratkartoffeln und Salat',
    price: 22.40,
    category: 'Pfannengerichte',
    allergens: [],
  },
  {
    id: '49',
    name: 'Pfeffer Pfanne',
    description: 'Schweinefilets, Rinderfilets, Lamm-Medaillon mit Pfeffersoße, grünen Bohnen, Kroketten und Salat',
    price: 23.50,
    category: 'Pfannengerichte',
    allergens: [],
  },
  {
    id: '50',
    name: 'Schnitzel Wiener Art',
    description: 'Schweinefleisch, Pommes frites, Gemüse und Salat',
    price: 15.10,
    category: 'Internationale Spezialitäten',
    allergens: ['Gluten', 'Ei'],
  },
  {
    id: '51',
    name: 'Cordon bleu vom Schwein',
    description: 'Pommes frites, Gemüse und Salat',
    price: 17.00,
    category: 'Internationale Spezialitäten',
    allergens: ['Gluten', 'Ei', 'Milch'],
  },
  {
    id: '52',
    name: 'Zwiebelschnitzel vom Schwein',
    description: 'mit Bratkartoffeln und Salat',
    price: 17.20,
    category: 'Internationale Spezialitäten',
    allergens: ['Gluten', 'Ei'],
  },
  {
    id: '53',
    name: 'Krustchen des Hauses',
    description: 'paniertes Schweineschnitzel mit Champignons, Spargel, Soße Hollandaise mit Käse überbacken, Gemüse und Kroketten',
    price: 18.40,
    category: 'Internationale Spezialitäten',
    allergens: ['Gluten', 'Ei', 'Milch'],
  },
  {
    id: '54',
    name: 'Jägerschnitzel',
    description: 'mit Pommes frites und Salat',
    price: 17.20,
    category: 'Internationale Spezialitäten',
    allergens: ['Gluten', 'Ei'],
  },
  {
    id: '55',
    name: 'Bauernschnitzel',
    description: 'paniertes Schweineschnitzel mit Käse gefüllt auf Rahmsoße mit Pommes frites und Salat',
    price: 19.00,
    category: 'Internationale Spezialitäten',
    allergens: ['Gluten', 'Ei', 'Milch'],
  },
  {
    id: '56',
    name: 'Bolognesenschnitzel',
    description: 'paniertes Schweineschnitzel mit Käse überbacken, Gemüse und Kroketten',
    price: 17.20,
    category: 'Internationale Spezialitäten',
    allergens: ['Gluten', 'Ei', 'Milch'],
  },
  {
    id: '57',
    name: 'Schweinelendchen Calvados',
    description: 'mit Äpfeln in Calvadosrahmsoße, Kroketten und Salat',
    price: 20.70,
    category: 'Internationale Spezialitäten',
    allergens: ['Milch'],
  },
  {
    id: '58',
    name: 'Schweinelendchen Diana',
    description: 'mit frischen Champignons in Rahmsoße nach Art des Hauses, Kroketten und Salat',
    price: 20.70,
    category: 'Internationale Spezialitäten',
    allergens: ['Milch'],
  },
  {
    id: '59',
    name: 'Schweinelendchen Monsuns',
    description: 'mit Sauce Bearnaise, Pommes frites und Salat',
    price: 20.70,
    category: 'Internationale Spezialitäten',
    allergens: ['Ei', 'Milch'],
  },
  {
    id: '60',
    name: 'Schweinelendchen Haus Ronneburg',
    description: 'mit Steinpilzsoße, Rösti und Salat',
    price: 22.40,
    category: 'Internationale Spezialitäten',
    allergens: [],
    notes: 'Haus-Spezialität',
  },
  {
    id: '61',
    name: 'Schweinelendchen Madagaskar',
    description: 'mit Pfeffersoße, Pommes frites und Salat',
    price: 20.70,
    category: 'Internationale Spezialitäten',
    allergens: [],
  },
  {
    id: '62',
    name: 'Lammkotelett',
    description: 'mit Kräuterbutter, Bratkartoffeln und Salat',
    price: 22.40,
    category: 'Internationale Spezialitäten',
    allergens: [],
  },
  {
    id: '63',
    name: 'Hähnchenbrustfilet',
    description: 'mit Kartoffelecken, Kräuterbutter und Salat',
    price: 19.00,
    category: 'Internationale Spezialitäten',
    allergens: [],
  },
  {
    id: '69',
    name: 'Rumpsteak Dalmacija',
    description: 'mit Knoblauchrahmsoße, Kroketten, Buttereis und Salat',
    price: 26.50,
    category: 'Steaks',
    allergens: ['Milch'],
    notes: '250g vom Lavastein-Grill',
  },
  {
    id: '70',
    name: 'Rumpsteak Alt Deutsch',
    description: 'mit gerösteten Zwiebeln, Bratkartoffeln und Salat',
    price: 26.70,
    category: 'Steaks',
    allergens: [],
    notes: '250g vom Lavastein-Grill',
  },
  {
    id: '71',
    name: 'Rumpsteak Madagaskar',
    description: 'mit grüner Pfeffersoße, Kroketten, Buttereis und Salat',
    price: 26.50,
    category: 'Steaks',
    allergens: ['Milch'],
    notes: '250g vom Lavastein-Grill',
  },
  {
    id: '72',
    name: 'Rumpsteak Grande',
    description: 'mit Pommes frites, würziger Kräuterbutter und Salat',
    price: 31.00,
    category: 'Steaks',
    allergens: [],
    notes: '300g vom Lavastein-Grill',
  },
  {
    id: '73',
    name: 'Rumpsteak nach Art des Hauses',
    description: 'mit Käse gefüllt, Pommes frites, Duvecreis und Salat',
    price: 26.70,
    category: 'Steaks',
    allergens: ['Milch'],
    notes: '250g vom Lavastein-Grill',
  },
  {
    id: '74',
    name: 'Filetsteak',
    description: 'Rinderlende mit würziger Kräuterbutter, Folienkartoffeln und Salat',
    price: 31.00,
    category: 'Steaks',
    allergens: [],
    notes: '250g vom Lavastein-Grill',
  },
  {
    id: '75',
    name: 'Pfeffersteak',
    description: 'Rinderlende mit grüner Pfeffersoße, Kroketten, grüne Bohnen und Salat',
    price: 31.00,
    category: 'Steaks',
    allergens: [],
    notes: '250g vom Lavastein-Grill',
  },
  {
    id: '76',
    name: 'Filetsteak mit Champignons',
    description: 'dazu Pommes frites, Buttereis und Salat',
    price: 31.00,
    category: 'Steaks',
    allergens: ['Milch'],
    notes: '250g vom Lavastein-Grill',
  },
  {
    id: '77',
    name: 'Filetsteak Grande',
    description: 'mit Bratkartoffeln, würziger Kräuterbutter und Salat',
    price: 36.50,
    category: 'Steaks',
    allergens: [],
    notes: '300g vom Lavastein-Grill',
  },
  {
    id: '78',
    name: 'Calamares gegrillt',
    description: 'ganz mit Kopf, mit Salzkartoffeln, Knoblauchsoße und Salat',
    price: 18.30,
    category: 'Fisch',
    allergens: ['Mollusken'],
  },
  {
    id: '79',
    name: 'Schollenfilets',
    description: 'mit Dillsoße, Salzkartoffeln und Salat',
    price: 19.40,
    category: 'Fisch',
    allergens: ['Fisch', 'Milch'],
  },
  {
    id: '80',
    name: 'Rotbarschfilets',
    description: 'mit Dillsoße, Butterreis und Salat',
    price: 19.40,
    category: 'Fisch',
    allergens: ['Fisch', 'Milch'],
  },
  {
    id: '81',
    name: 'Zanderfilets Dalmatinischer Art',
    description: 'Butterreis, Petersilienkartoffeln, Weißweinsoße und Salat',
    price: 21.70,
    category: 'Fisch',
    allergens: ['Fisch', 'Milch'],
    notes: 'Kroatische Art',
  },
  {
    id: '82',
    name: 'Lachsfilet vom Grill',
    description: 'mit Zitronensoße, Salzkartoffeln, Broccoli und Salat',
    price: 20.10,
    category: 'Fisch',
    allergens: ['Fisch'],
  },
  {
    id: '83',
    name: 'Forelle (Blau oder Müllerin Art)',
    description: 'mit Salzkartoffeln, Blattspinat, zerlassener Butter und Salat',
    price: 17.00,
    category: 'Fisch',
    allergens: ['Fisch', 'Milch'],
  },
  {
    id: '84',
    name: 'Vegetarischer Teller',
    description: 'verschiedene Gemüsesorten, gebackener Käse, Champignons, Ei und Spargel',
    price: 12.50,
    category: 'Vegetarisch',
    allergens: ['Milch', 'Ei', 'Gluten'],
  },
  {
    id: '85',
    name: 'Gemüse-Gratin',
    description: 'verschiedene Gemüsesorten mit Sauce Hollandaise und Käse überbacken',
    price: 13.20,
    category: 'Vegetarisch',
    allergens: ['Milch', 'Ei'],
  },
  {
    id: '86',
    name: 'Frisch gedünstetes Gemüse',
    description: 'verschiedene Gemüsesorten gedünstet mit saurer Sahne',
    price: 12.50,
    category: 'Vegetarisch',
    allergens: ['Milch'],
  },
  {
    id: '88',
    name: 'Pikanter Bauernsalat',
    description: 'mit geriebenem Käse',
    price: 10.20,
    category: 'Salatplatten',
    allergens: ['Milch'],
  },
  {
    id: '89',
    name: 'Salatplatte Kroatia',
    description: 'Salate der Saison mit Schinken, Oliven und Ei',
    price: 10.70,
    category: 'Salatplatten',
    allergens: ['Ei'],
  },
  {
    id: '90',
    name: 'Salat Haus Ronneburg',
    description: 'Salate der Saison mit gebratenen Champignonköpfen und Knoblauch',
    price: 11.10,
    category: 'Salatplatten',
    allergens: [],
    notes: 'Haus-Spezialität',
  },
  {
    id: '91',
    name: 'Griechischer Salat',
    description: 'Tomaten, Gurken, Paprika, Zwiebeln, Käse, Oliven und Peperoni',
    price: 11.50,
    category: 'Salatplatten',
    allergens: ['Milch'],
  },
  {
    id: '92',
    name: 'Salatschüssel Nicoise',
    description: 'Salate der Saison mit Thunfisch, Ei und Oliven',
    price: 10.80,
    category: 'Salatplatten',
    allergens: ['Fisch', 'Ei'],
  },
  {
    id: '93',
    name: 'Salatteller',
    description: 'mit gegrillten Putenbruststreifen',
    price: 15.90,
    category: 'Salatplatten',
    allergens: [],
  },
  {
    id: '94',
    name: 'Schnitzel Wiener Art Rotkäppchen',
    description: 'mit Pommes frites und Salat',
    price: 9.50,
    category: 'Für Kinder',
    allergens: ['Gluten', 'Ei'],
  },
  {
    id: '95',
    name: 'Pola Pola für Kinder',
    description: 'ein Spieß und zwei Cevapcici mit Pommes frites, Duvecreis und Salat',
    price: 9.40,
    category: 'Für Kinder',
    allergens: ['Gluten'],
  },
  {
    id: '955',
    name: 'Cevapcici für Kinder (4 Stück)',
    description: 'mit Pommes frites und Salat',
    price: 9.40,
    category: 'Für Kinder',
    allergens: ['Gluten'],
  },
  {
    id: '96',
    name: 'Chicken-Nuggets',
    description: 'mit Pommes frites und Salat',
    price: 9.00,
    category: 'Für Kinder',
    allergens: ['Gluten', 'Ei'],
  },
];
